### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by 7system7** [matheusfillipe/joplin-snippets#3]
After I install every deps, and the API token has been set up, the plugin does not working at all. And there is no any log in syslog.

https://user-images.githubusercontent.com/3964568/135283554-3e17fd1c-3a72-401d-acf4-f10f90fdd2ff.mp4

## System

```
$ neofetch
            .-/+oossssoo+/-.               system7@AMBER 
        `:+ssssssssssssssssss+:`           ------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 21.04 x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: 20QV00CEGE ThinkPad X1 Extreme 2nd 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.11.0-36-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 4 days, 4 hours, 30 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2463 (dpkg), 71 (flatpak), 15 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.1.4 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 2560x1080 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: GNOME 3.38.4 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Adwaita 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: WhiteSur-light-solid [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Papirus [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: guake 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: Intel i9-9880H (16) @ 4.800GHz 
    .ossssssssssssssssssdMMMNysssso.       GPU: NVIDIA GeForce GTX 1650 Mobile / Max-Q 
      -+sssssssssssssssssyyyssss+-         GPU: Intel CoffeeLake-H GT2 [UHD Graphics 630] 
        `:+ssssssssssssssssss+:`           Memory: 24012MiB / 64048MiB 
            .-/+oossssoo+/-.
                                                                   
                                                                   
```

**Comment by matheusfillipe** [comment]
First of all, just to make sure, ensure you do have web clipper server enabled (Which I imagine you do). Might look like this:
![image](https://user-images.githubusercontent.com/24435787/135309888-ea1cd006-9ddd-40f2-879d-952723a23df4.png)

Pay attention to copy the token without whitespaces to the ulauncher extension and make sure the port number is 41184 ("Status: Started on port 41184" on the joplin web clipper screen). As of now this port number is hardcoded and automatically discovering it is not yet implemented. It might be different if this port is already bound on your system so check that out as well. 

You can confirm the server is running and accessible with this curl command:
```
curl --silent http://localhost:41184/ping\?token\=your_token_here
```
And it will respond with "JoplinClipperServer". Joplin will try the next port in case there is a problem so try with 41185, 41186 and so on in case you are not sure.

After you made sure the joplin clipper api is running and that it is on port 41184, but you still have a problem kill your current ulauncher instance `killall ulauncher -9` and start ulauncher with verbose from a terminal: `ulauncher -vvvv`. Issue your usual trigger command and try to test it again like on the video you sent. If there is an error it will be displayed there.

Another thing to notice is that there is a default notebook this extension will look inside. It won't search your entire joplin notebooks, by default it will look inside a notebook called "snippets" (you can change it on the settings) so that has to exist and there has to be a note containing "hello" on its title inside that notebook for your test to be correct.

**Comment by 7system7** [comment]
Firstly, thank you for your quick answer. I did not know that, ulauncher has a verbose run mode. I wanted to find the logs in syslog. So, following your guide, I checked the log and it writes:

```
...
com.github.matheusfillipe.joplin-snippets | 2021-09-29 19:55:00,571 | DEBUG | urllib3.connectionpool: _new_conn() | Starting new HTTP connection (1): localhost:41184
com.github.matheusfillipe.joplin-snippets | 2021-09-29 19:55:00,579 | DEBUG | urllib3.connectionpool: _make_request() | http://localhost:41184 "GET /folders/<api-token>&page=1 HTTP/1.1" 200 None
com.github.matheusfillipe.joplin-snippets | 2021-09-29 19:55:00,580 | DEBUG | ulauncher.api.client.Client: send() | Send message
2021-09-29 19:55:00,582 | DEBUG | ulauncher.api.server.ExtensionController: handleMessage() | Incoming response (KeywordQueryEvent, RenderResultListAction) from "com.github.matheusfillipe.joplin-snippets"
2021-09-29 19:55:00,583 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2021-09-29 19:55:04,728 | DEBUG | ulauncher.utils.display: get_screens() | Found 1 monitor(s)
2021-09-29 19:55:04,729 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 2560, H: 1080
2021-09-29 19:55:04,734 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
...
```

After that I realized, it actually works on my machine, but there is no any results for my keyword.

The bigger problem was that, I did not fully understand what the plugin was for... :smile: I thought that, it can search a keyword in a specific notebook in Joplin, and after I choose a result, it opens in the app right there. (Btw, It would be great.)

So, a word like a hundred; thank you for this awesome extension, it is handy for me too, because I am a developer. **If you do not mind, I would share w/ you only one note: may it would be a good idea to show "No results" when there is no any result for a keyword.**

I apologize cause' I wasted your time.

**Comment by matheusfillipe** [comment]
Oh no the idea for the plugin was more to quick save and paste "snippets" of text from joplin. Like you copy some command or anything you find useful and create a note of it with nc then get it back with n, more like a clipboard manager functionality. Also try creating a json code note, it can then fetch an item from each of the keys of the json.

You can already do a search over notes title and body using Ctrl+P on the joplin electron app and I am sure the CLI has that too.

Yes "No Results" is a reasonable idea. I updated it now adding it.
